import { provideHttpClient } from '@angular/common/http';
import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
} from '@angular/core';
import {
  ArrowRight,
  ArrowUpRight,
  Bot,
  CakeSlice,
  CalendarCheck,
  Check,
  CreditCard,
  Dumbbell,
  FileText,
  Gift,
  Landmark,
  LayoutDashboard,
  LucideAngularModule,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Palette,
  PawPrint,
  Rocket,
  Stethoscope,
  UserRoundCheck,
  Workflow,
  Wrench,
  X,
} from 'lucide-angular';

/** Solo se empaquetan los iconos listados aca, no la libreria entera. */
const ICONOS = {
  ArrowRight,
  ArrowUpRight,
  Bot,
  CakeSlice,
  CalendarCheck,
  Check,
  CreditCard,
  Dumbbell,
  FileText,
  Gift,
  Landmark,
  LayoutDashboard,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Palette,
  PawPrint,
  Rocket,
  Stethoscope,
  UserRoundCheck,
  Workflow,
  Wrench,
  X,
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideHttpClient(),
    importProvidersFrom(LucideAngularModule.pick(ICONOS)),
  ],
};
